### ISSUE TITLE
Doesn't want to run

### ISSUE THREAD

**Issue by CounterGambit** [jrg94/color-picker#6]
This tool would be very useful for me, but it doesn't want to run!

**Comment by jrg94** [comment]
I'm excited that you want to use it! What issue are you running into?

**Comment by CounterGambit** [comment]
I'm trying to run the program, and nothing I do is getting it to run.

**Comment by jrg94** [comment]
Can you share some examples? Or show me the error you're getting?

**Comment by CounterGambit** [comment]
I'm not getting any errors. Which is even more confusing. I'm simply trying to run the program, and nothing happens.

**Comment by jrg94** [comment]
Hmm! I haven't used this in awhile. Let me try to run it.

**Comment by CounterGambit** [comment]
if you get it to work, mind providing a step by step, just to make sure I'm not missing something so obvious, and my brain is just too fried to think of it... lol

**Comment by jrg94** [comment]
Since there's some interest, I'll probably convert this into a proper package so you can just `pip` and run.

**Comment by CounterGambit** [comment]
I have no idea what you mean by pip... if that's a python term, I'm still new to it.

**Comment by jrg94** [comment]
No worries! I'll put together a guide 😄

**Comment by jrg94** [comment]
Okay, so we should be in good shape now! If you head to the homepage of this repo, there'll be directions for this. Let me know if you run into trouble. If you need more help with `pip`, I can help with that as well.

**Comment by CounterGambit** [comment]
Okay, I see now a Setup.py, do I just double click on that, or do I need to do something else first? python confuses me!

**Comment by jrg94** [comment]
You should be able to run `pip install pso2-color-picker`. Then you can run `color-picker` directly.

**Comment by CounterGambit** [comment]
Do I have to put the color picker files in a specific location for the pip install to work? because I tried that, and get a syntaxerror: invalid syntax

**Comment by jrg94** [comment]
Interesting! What version of Python are you using? Also, does the pip install fail?

**Comment by CounterGambit** [comment]
I am using the latest version of Python, 3.9.0. And yes the install fails, it comes back with "Syntax Error: Invalid Syntax"

**Comment by jrg94** [comment]
Are you running the command from the command line? This worked for me:
![image](https://user-images.githubusercontent.com/11050412/101540099-86c1d300-396d-11eb-800a-990dc913e85c.png)

**Comment by CounterGambit** [comment]
I found the problem. and had to reinstall python.

**Comment by CounterGambit** [comment]
Thanks for the help, and I'm glad it's resolved
